version: '3.8'

services:
  app:
    image: demo-app
    build: .
    ports:
      - "8080:8080"  # Asegúrate de que esto esté presente
    environment:
      SPRING_APPLICATION_NAME: demo
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/votaciones
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: votaciones
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8081:8080"  # Esto está bien
